### ISSUE TITLE
Details of NOC architecture

### ISSUE THREAD

**Issue by aqianwang** [tjiiv-cprg/MonoRUn#3]
Dear author, 

Thanks for your wonderful work. I felt doubt about the noc architecture after reading the program. Could you kindly help me address it? In the code, it seems the object rotation is composed in the noc and the object dimension is decomposed (https://github.com/tjiiv-cprg/MonoRUn/blob/main/monorun/core/bbox_3d/coord_coder/noc_coder.py#L17) . I am curious why do not decompose the object rotation as did in the object dimension. 

Best regards.

**Comment by Lakonik** [comment]
Thank you for your interest in our work.
By definition, NOC = object_coordinates / dimensions. This conversion makes NOC invariant to object size and better correspond to certain parts of categorical objects. Thus, rotation is not involved in this conversion.
