### ISSUE TITLE
No module named 'monorun.ops.least_squares._ext'

### ISSUE THREAD

**Issue by dcsrgh** [tjiiv-cprg/MonoRUn#5]
There is a error named "No module named 'monorun.ops.least_squares._ext'", when I run the code.
How can I solve it, please.

**Comment by Lakonik** [comment]
This indicates that the PnP lib is not found. You can follow INSTALL.md to build the PnP module.

**Comment by dcsrgh** [comment]
Thank you for your approach. I installed the wrong version of the Ceres, but now I have a new problem when follow INSTAll.md.
This is "gcc: error: /config:没有这个文件或目录", when I run "python setup.py" in "Clone and build".

**Comment by Lakonik** [comment]
Can you show the full error message?

**Comment by dcsrgh** [comment]
(monorun) dl@dl:~/code/zzm/monorun/monorun/ops/least_squares$ python setup.py 
gcc: error: /config: 没有那个文件或目录
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    os.getenv('Ceres_DIR') + '/lib/libceres.so'],
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by Lakonik** [comment]
Please export these environment variables after installing Ceres as instructed in INSTALL.md
```
export CERES_INCLUDE_DIRS=$PWD/include
export Ceres_DIR=$PWD/build
```
and don't switch the terminal before finishing building the PnP module

**Comment by dcsrgh** [comment]
This is a point that deserves special attention.
In this way, I ran the code successfully and hope no problems tomorrow.
Thank you very much for your patience.
